### ISSUE TITLE
npmjs.com availability

### ISSUE THREAD

**Issue by pram** [SummitRoute/react-structured-filter#2]
Could you make this available on https://www.npmjs.com?

**Comment by 0xdabbad00** [comment]
No, this project is no longer under active development.  You're welcome to add it there, but I don't do enough web development anymore to learn all of the tooling involved.

**Comment by joshcarr** [comment]
@pram  I have an actively maintained fork with many updates: https://github.com/joshcarr/react-structured-filter

and on npm: https://www.npmjs.com/package/react-structured-filter

**Comment by pram** [comment]
@joshcarr Thanks. I'll take a look as soon as I can
