### ISSUE TITLE
Error when attempting to import with webpack

### ISSUE THREAD

**Issue by ttrmw** [SummitRoute/react-structured-filter#4]
```
15:32:53 client.1 | ERROR in ./~/react-datetime/css/react-datetime.css
15:32:53 client.1 | Module parse failed: /redacted/node_modules/react-datetime/css/react-datetime.css Unexpected token (5:0)
```

Solved by adding:

```
config.module.loaders.push(
  {
    test: /\.css$/,
    loader: "style-loader!css-loader"
  }
);
```

to my webpack config. This is probably a super common set up so maybe worth adding to the README. Happy to do a PR next week.

**Comment by 0xdabbad00** [comment]
I saw you closed out your other issue.  Is this still a concern as well?

**Comment by ttrmw** [comment]
The other issue was me being silly. This is IMO worth adding to the docs, but I'm happy to submit a PR for it when I get a chance.

**Comment by 0xdabbad00** [comment]
No need for a PR. I'm no longer maintaining the project.

**Comment by joshcarr** [comment]
@ttrmw  I have an actively maintained fork with many updates that imports nicely with webpack: https://github.com/joshcarr/react-structured-filter

and on npm: https://www.npmjs.com/package/react-structured-filter

**Comment by ttrmw** [comment]
Thanks @joshcarr. I'm not currently working on the project that led me here, but when I return to it I will take a look!
