### ISSUE TITLE
make it free from Bootstrap

### ISSUE THREAD

**Issue by achtan** [SummitRoute/react-structured-filter#6]
i am using Material Design in my project, so i don't want to import BS... :(

**Comment by 0xdabbad00** [comment]
It's best to just fork and make your changes.  This project is no longer being maintained.

**Comment by joshcarr** [comment]
@achtan I have an actively maintained fork with many updates that does not rely on Bootstrap or any other libs: https://github.com/joshcarr/react-structured-filter

and on npm: https://www.npmjs.com/package/react-structured-filter
